version: '3'

services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - './nginx/conf:/etc/nginx/conf.d'
      - './nginx/www:/var/www/html'

  django:
    image: django:v2
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./django/univ:/app
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 --timeout 90 config.wsgi:application"

networks:
  default:
    external:
      name: web-server
