# Generated by Django 4.1.1 on 2022-10-20 16:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='board',
            new_name='board_data',
        ),
    ]
